let data=[
    {
        "IdProducto": 505,
        "CodigoMercaderia": "6",
        "IdTipoExistencia": 1,
        "IdSubFamiliaProducto": 0,
        "IdModelo": 0,
        "IdLineaProducto": 0,
        "IdUnidadMedida": 58,
        "IdTipoSistemaISC": 0,
        "IdTipoAfectacionIGV": 1,
        "IdTipoPrecio": 1,
        "IdFabricante": 0,
        "IdMoneda": 1,
        "IdTipoTributo": 1,
        "IdOrigenMercaderia": 1,
        "SaldoFisico": "",
        "StockMinimo": "",
        "StockMaximo": "",
        "PesoUnitario": "",
        "PrecioUnitario": 28,
        "UltimoPrecio": 25,
        "FechaVencimiento": "",
        "Foto": "https://sfact.pe/15325807773/assets/img/Mercaderia/505/AFTAR.JPG",
        "NumeroSerie": "",
        "NumeroMotor": "",
        "NumeroPlaca": "",
        "Ano": "",
        "Color": "",
        "Textura": "",
        "Talla": "",
        "Beneficio": "",
        "Tamano": "",
        "OtroDato": "",
        "CodigoBarras": "",
        "AfectoIGV": "",
        "AfectoISC": "",
        "ISC": "",
        "SujetoPercepcionVenta": "0",
        "TasaNormal": "",
        "TasaAgentePercepcion": "",
        "CostoPromedioPonderado": "",
        "MargenPorcentaje": "",
        "MargenUtilidad": "",
        "ValorVenta": "",
        "ValorIGV": "",
        "PrecioPromedioCompra": "",
        "FechaUltimoPrecio": "",
        "EstadoCampoCalculo": "0",
        "AfectoICBPER": "0",
        "AfectoBonificacion": "0",
        "CodigoMercaderia2": "",
        "CodigoAlterno": "",
        "IdProveedor": "",
        "Referencia": "",
        "TipoDescuento": "0",
        "ValorDescuento": 0,
        "NumeroPiezas": "",
        "IdMonedaCompra": 1,
        "CostoUnitarioCompra": "",
        "PrecioUnitarioCompra": "",
        "ReferenciaProveedor": "",
        "FechaIngresoCompra": "",
        "Aplicacion": "",
        "TipoCambioCompra": "",
        "FechaIngreso": "",
        "CodigoCorrelativoAutomatico": "",
        "IndicadorCodigoPropio": "",
        "NombreFabricante": "NO ESPECIFICADO",
        "NombreTipoExistencia": "MERCADERIA",
        "AbreviaturaUnidadMedida": "UND",
        "NombreMoneda": "SOLES",
        "NombreFamiliaProducto": "NO ESPECIFICADO",
        "IdFamiliaProducto": 0,
        "NombreSubFamiliaProducto": "NO ESPECIFICADO",
        "NombreLineaProducto": "NO ESPECIFICADO",
        "NombreMarca": "NO ESPECIFICADO",
        "IdMarca": 0,
        "NombreModelo": "NO ESPECIFICADO",
        "NombreProducto": "AFTAR PARTY",
        "IndicadorEstado": "A",
        "UsuarioRegistro": "ABDUL",
        "FechaRegistro": "2022-06-28 18:03:56",
        "UsuarioModificacion": "",
        "FechaModificacion": "",
        "EstadoProducto": "1",
        "NombreLargoProducto": "AFTAR PARTY",
        "CodigoTipoAfectacionIGV": "10",
        "CodigoTipoSistemaISC": "",
        "CodigoTipoPrecio": "01",
        "BloquearTipoMercaderia": 0,
        "IndicadorAfectoICBPER": false,
        "IndicadorEstadoProducto": true,
        "AnotacionesPlatoProducto": [],
        "IndicadorAfectoBonificacion": false,
        "CantidadBonificaciones": 0,
        "Bonificaciones": []
    },
    {
        "IdProducto": 504,
        "CodigoMercaderia": "5",
        "IdTipoExistencia": 1,
        "IdSubFamiliaProducto": 0,
        "IdModelo": 0,
        "IdLineaProducto": 0,
        "IdUnidadMedida": 58,
        "IdTipoSistemaISC": 0,
        "IdTipoAfectacionIGV": 1,
        "IdTipoPrecio": 1,
        "IdFabricante": 0,
        "IdMoneda": 1,
        "IdTipoTributo": 1,
        "IdOrigenMercaderia": 1,
        "SaldoFisico": "",
        "StockMinimo": "",
        "StockMaximo": "",
        "PesoUnitario": "",
        "PrecioUnitario": 18,
        "UltimoPrecio": 18,
        "FechaVencimiento": "",
        "Foto": "https://sfact.pe/15325807773/assets/img/Mercaderia/504/183560869_2935633596759103_8725935312658441377_N.JPG",
        "NumeroSerie": "",
        "NumeroMotor": "",
        "NumeroPlaca": "",
        "Ano": "",
        "Color": "",
        "Textura": "",
        "Talla": "",
        "Beneficio": "",
        "Tamano": "",
        "OtroDato": "",
        "CodigoBarras": "",
        "AfectoIGV": "",
        "AfectoISC": "",
        "ISC": "",
        "SujetoPercepcionVenta": "0",
        "TasaNormal": "",
        "TasaAgentePercepcion": "",
        "CostoPromedioPonderado": "",
        "MargenPorcentaje": "",
        "MargenUtilidad": "",
        "ValorVenta": "",
        "ValorIGV": "",
        "PrecioPromedioCompra": "",
        "FechaUltimoPrecio": "",
        "EstadoCampoCalculo": "0",
        "AfectoICBPER": "0",
        "AfectoBonificacion": "0",
        "CodigoMercaderia2": "",
        "CodigoAlterno": "",
        "IdProveedor": "",
        "Referencia": "",
        "TipoDescuento": "0",
        "ValorDescuento": 0,
        "NumeroPiezas": "",
        "IdMonedaCompra": 1,
        "CostoUnitarioCompra": "",
        "PrecioUnitarioCompra": "",
        "ReferenciaProveedor": "",
        "FechaIngresoCompra": "",
        "Aplicacion": "",
        "TipoCambioCompra": "",
        "FechaIngreso": "",
        "CodigoCorrelativoAutomatico": "",
        "IndicadorCodigoPropio": "",
        "NombreFabricante": "NO ESPECIFICADO",
        "NombreTipoExistencia": "MERCADERIA",
        "AbreviaturaUnidadMedida": "UND",
        "NombreMoneda": "SOLES",
        "NombreFamiliaProducto": "NO ESPECIFICADO",
        "IdFamiliaProducto": 0,
        "NombreSubFamiliaProducto": "NO ESPECIFICADO",
        "NombreLineaProducto": "NO ESPECIFICADO",
        "NombreMarca": "NO ESPECIFICADO",
        "IdMarca": 0,
        "NombreModelo": "NO ESPECIFICADO",
        "NombreProducto": "BIRYANI DE POLLO",
        "IndicadorEstado": "A",
        "UsuarioRegistro": "ABDUL",
        "FechaRegistro": "2022-06-28 18:02:35",
        "UsuarioModificacion": "",
        "FechaModificacion": "",
        "EstadoProducto": "1",
        "NombreLargoProducto": "BIRYANI DE POLLO",
        "CodigoTipoAfectacionIGV": "10",
        "CodigoTipoSistemaISC": "",
        "CodigoTipoPrecio": "01",
        "BloquearTipoMercaderia": 0,
        "IndicadorAfectoICBPER": false,
        "IndicadorEstadoProducto": true,
        "AnotacionesPlatoProducto": [],
        "IndicadorAfectoBonificacion": false,
        "CantidadBonificaciones": 0,
        "Bonificaciones": []
    },
    {
        "IdProducto": 500,
        "CodigoMercaderia": "1",
        "IdTipoExistencia": 1,
        "IdSubFamiliaProducto": 0,
        "IdModelo": 0,
        "IdLineaProducto": 0,
        "IdUnidadMedida": 58,
        "IdTipoSistemaISC": 0,
        "IdTipoAfectacionIGV": 1,
        "IdTipoPrecio": 1,
        "IdFabricante": 0,
        "IdMoneda": 1,
        "IdTipoTributo": 1,
        "IdOrigenMercaderia": 1,
        "SaldoFisico": "",
        "StockMinimo": "",
        "StockMaximo": "",
        "PesoUnitario": "",
        "PrecioUnitario": 20,
        "UltimoPrecio": "",
        "FechaVencimiento": "",
        "Foto": "https://sfact.pe/15325807773/assets/img/Mercaderia/500/CHICKEN.JPG",
        "NumeroSerie": "",
        "NumeroMotor": "",
        "NumeroPlaca": "",
        "Ano": "",
        "Color": "",
        "Textura": "",
        "Talla": "",
        "Beneficio": "",
        "Tamano": "",
        "OtroDato": "",
        "CodigoBarras": "",
        "AfectoIGV": "",
        "AfectoISC": "",
        "ISC": "",
        "SujetoPercepcionVenta": "0",
        "TasaNormal": "",
        "TasaAgentePercepcion": "",
        "CostoPromedioPonderado": "",
        "MargenPorcentaje": "",
        "MargenUtilidad": "",
        "ValorVenta": "",
        "ValorIGV": "",
        "PrecioPromedioCompra": "",
        "FechaUltimoPrecio": "",
        "EstadoCampoCalculo": "0",
        "AfectoICBPER": "0",
        "AfectoBonificacion": "0",
        "CodigoMercaderia2": "",
        "CodigoAlterno": "",
        "IdProveedor": "",
        "Referencia": "",
        "TipoDescuento": "0",
        "ValorDescuento": 0,
        "NumeroPiezas": "",
        "IdMonedaCompra": 1,
        "CostoUnitarioCompra": "",
        "PrecioUnitarioCompra": "",
        "ReferenciaProveedor": "",
        "FechaIngresoCompra": "",
        "Aplicacion": "",
        "TipoCambioCompra": "",
        "FechaIngreso": "",
        "CodigoCorrelativoAutomatico": "",
        "IndicadorCodigoPropio": "",
        "NombreFabricante": "NO ESPECIFICADO",
        "NombreTipoExistencia": "MERCADERIA",
        "AbreviaturaUnidadMedida": "UND",
        "NombreMoneda": "SOLES",
        "NombreFamiliaProducto": "NO ESPECIFICADO",
        "IdFamiliaProducto": 0,
        "NombreSubFamiliaProducto": "NO ESPECIFICADO",
        "NombreLineaProducto": "NO ESPECIFICADO",
        "NombreMarca": "NO ESPECIFICADO",
        "IdMarca": 0,
        "NombreModelo": "NO ESPECIFICADO",
        "NombreProducto": "CHICKEN KARAHI",
        "IndicadorEstado": "A",
        "UsuarioRegistro": "ABDUL",
        "FechaRegistro": "2022-06-28 18:00:42",
        "UsuarioModificacion": "ABDUL",
        "FechaModificacion": "2022-06-28 18:03:15",
        "EstadoProducto": "1",
        "NombreLargoProducto": "CHICKEN KARAHI",
        "CodigoTipoAfectacionIGV": "10",
        "CodigoTipoSistemaISC": "",
        "CodigoTipoPrecio": "01",
        "BloquearTipoMercaderia": 0,
        "IndicadorAfectoICBPER": false,
        "IndicadorEstadoProducto": true,
        "AnotacionesPlatoProducto": [],
        "IndicadorAfectoBonificacion": false,
        "CantidadBonificaciones": 0,
        "Bonificaciones": []
    },
    {
        "IdProducto": 502,
        "CodigoMercaderia": "3",
        "IdTipoExistencia": 1,
        "IdSubFamiliaProducto": 0,
        "IdModelo": 0,
        "IdLineaProducto": 0,
        "IdUnidadMedida": 58,
        "IdTipoSistemaISC": 0,
        "IdTipoAfectacionIGV": 1,
        "IdTipoPrecio": 1,
        "IdFabricante": 0,
        "IdMoneda": 1,
        "IdTipoTributo": 1,
        "IdOrigenMercaderia": 1,
        "SaldoFisico": "",
        "StockMinimo": "",
        "StockMaximo": "",
        "PesoUnitario": "",
        "PrecioUnitario": 7,
        "UltimoPrecio": 5,
        "FechaVencimiento": "",
        "Foto": "https://sfact.pe/15325807773/assets/img/Mercaderia/502/175958682_2924463104542819_85906635328070477_N.JPG",
        "NumeroSerie": "",
        "NumeroMotor": "",
        "NumeroPlaca": "",
        "Ano": "",
        "Color": "",
        "Textura": "",
        "Talla": "",
        "Beneficio": "",
        "Tamano": "",
        "OtroDato": "",
        "CodigoBarras": "",
        "AfectoIGV": "",
        "AfectoISC": "",
        "ISC": "",
        "SujetoPercepcionVenta": "0",
        "TasaNormal": "",
        "TasaAgentePercepcion": "",
        "CostoPromedioPonderado": "",
        "MargenPorcentaje": "",
        "MargenUtilidad": "",
        "ValorVenta": "",
        "ValorIGV": "",
        "PrecioPromedioCompra": "",
        "FechaUltimoPrecio": "",
        "EstadoCampoCalculo": "0",
        "AfectoICBPER": "0",
        "AfectoBonificacion": "0",
        "CodigoMercaderia2": "",
        "CodigoAlterno": "",
        "IdProveedor": "",
        "Referencia": "",
        "TipoDescuento": "0",
        "ValorDescuento": 0,
        "NumeroPiezas": "",
        "IdMonedaCompra": 1,
        "CostoUnitarioCompra": "",
        "PrecioUnitarioCompra": "",
        "ReferenciaProveedor": "",
        "FechaIngresoCompra": "",
        "Aplicacion": "",
        "TipoCambioCompra": "",
        "FechaIngreso": "",
        "CodigoCorrelativoAutomatico": "",
        "IndicadorCodigoPropio": "",
        "NombreFabricante": "NO ESPECIFICADO",
        "NombreTipoExistencia": "MERCADERIA",
        "AbreviaturaUnidadMedida": "UND",
        "NombreMoneda": "SOLES",
        "NombreFamiliaProducto": "NO ESPECIFICADO",
        "IdFamiliaProducto": 0,
        "NombreSubFamiliaProducto": "NO ESPECIFICADO",
        "NombreLineaProducto": "NO ESPECIFICADO",
        "NombreMarca": "NO ESPECIFICADO",
        "IdMarca": 0,
        "NombreModelo": "NO ESPECIFICADO",
        "NombreProducto": "HALWA",
        "IndicadorEstado": "A",
        "UsuarioRegistro": "ABDUL",
        "FechaRegistro": "2022-06-28 18:01:48",
        "UsuarioModificacion": "",
        "FechaModificacion": "",
        "EstadoProducto": "1",
        "NombreLargoProducto": "HALWA",
        "CodigoTipoAfectacionIGV": "10",
        "CodigoTipoSistemaISC": "",
        "CodigoTipoPrecio": "01",
        "BloquearTipoMercaderia": 0,
        "IndicadorAfectoICBPER": false,
        "IndicadorEstadoProducto": true,
        "AnotacionesPlatoProducto": [],
        "IndicadorAfectoBonificacion": false,
        "CantidadBonificaciones": 0,
        "Bonificaciones": []
    },
    {
        "IdProducto": 507,
        "CodigoMercaderia": "8",
        "IdTipoExistencia": 1,
        "IdSubFamiliaProducto": 0,
        "IdModelo": 0,
        "IdLineaProducto": 0,
        "IdUnidadMedida": 58,
        "IdTipoSistemaISC": 0,
        "IdTipoAfectacionIGV": 1,
        "IdTipoPrecio": 1,
        "IdFabricante": 0,
        "IdMoneda": 1,
        "IdTipoTributo": 1,
        "IdOrigenMercaderia": 1,
        "SaldoFisico": "",
        "StockMinimo": "",
        "StockMaximo": "",
        "PesoUnitario": "",
        "PrecioUnitario": 20,
        "UltimoPrecio": 20,
        "FechaVencimiento": "",
        "Foto": "https://sfact.pe/15325807773/assets/img/nocover.png",
        "NumeroSerie": "",
        "NumeroMotor": "",
        "NumeroPlaca": "",
        "Ano": "",
        "Color": "",
        "Textura": "",
        "Talla": "",
        "Beneficio": "",
        "Tamano": "",
        "OtroDato": "",
        "CodigoBarras": "",
        "AfectoIGV": "",
        "AfectoISC": "",
        "ISC": "",
        "SujetoPercepcionVenta": "0",
        "TasaNormal": "",
        "TasaAgentePercepcion": "",
        "CostoPromedioPonderado": "",
        "MargenPorcentaje": "",
        "MargenUtilidad": "",
        "ValorVenta": "",
        "ValorIGV": "",
        "PrecioPromedioCompra": "",
        "FechaUltimoPrecio": "",
        "EstadoCampoCalculo": "",
        "AfectoICBPER": "0",
        "AfectoBonificacion": "0",
        "CodigoMercaderia2": "",
        "CodigoAlterno": "",
        "IdProveedor": "",
        "Referencia": "",
        "TipoDescuento": "0",
        "ValorDescuento": 0,
        "NumeroPiezas": "",
        "IdMonedaCompra": 1,
        "CostoUnitarioCompra": "",
        "PrecioUnitarioCompra": "",
        "ReferenciaProveedor": "",
        "FechaIngresoCompra": "",
        "Aplicacion": "",
        "TipoCambioCompra": "",
        "FechaIngreso": "",
        "CodigoCorrelativoAutomatico": "",
        "IndicadorCodigoPropio": "",
        "NombreFabricante": "NO ESPECIFICADO",
        "NombreTipoExistencia": "MERCADERIA",
        "AbreviaturaUnidadMedida": "UND",
        "NombreMoneda": "SOLES",
        "NombreFamiliaProducto": "NO ESPECIFICADO",
        "IdFamiliaProducto": 0,
        "NombreSubFamiliaProducto": "NO ESPECIFICADO",
        "NombreLineaProducto": "NO ESPECIFICADO",
        "NombreMarca": "NO ESPECIFICADO",
        "IdMarca": 0,
        "NombreModelo": "NO ESPECIFICADO",
        "NombreProducto": "HELADO ARABE",
        "IndicadorEstado": "A",
        "UsuarioRegistro": "ABDUL",
        "FechaRegistro": "2022-06-29 18:46:32",
        "UsuarioModificacion": "",
        "FechaModificacion": "",
        "EstadoProducto": "1",
        "NombreLargoProducto": "HELADO ARABE",
        "CodigoTipoAfectacionIGV": "10",
        "CodigoTipoSistemaISC": "",
        "CodigoTipoPrecio": "01",
        "BloquearTipoMercaderia": 0,
        "IndicadorAfectoICBPER": false,
        "IndicadorEstadoProducto": true,
        "AnotacionesPlatoProducto": [],
        "IndicadorAfectoBonificacion": false,
        "CantidadBonificaciones": 0,
        "Bonificaciones": []
    },
    {
        "IdProducto": 503,
        "CodigoMercaderia": "4",
        "IdTipoExistencia": 1,
        "IdSubFamiliaProducto": 0,
        "IdModelo": 0,
        "IdLineaProducto": 0,
        "IdUnidadMedida": 58,
        "IdTipoSistemaISC": 0,
        "IdTipoAfectacionIGV": 1,
        "IdTipoPrecio": 1,
        "IdFabricante": 0,
        "IdMoneda": 1,
        "IdTipoTributo": 1,
        "IdOrigenMercaderia": 1,
        "SaldoFisico": "",
        "StockMinimo": "",
        "StockMaximo": "",
        "PesoUnitario": "",
        "PrecioUnitario": 20,
        "UltimoPrecio": 20,
        "FechaVencimiento": "",
        "Foto": "https://sfact.pe/15325807773/assets/img/Mercaderia/503/179960288_2930300483959081_1774836175152837159_N.JPG",
        "NumeroSerie": "",
        "NumeroMotor": "",
        "NumeroPlaca": "",
        "Ano": "",
        "Color": "",
        "Textura": "",
        "Talla": "",
        "Beneficio": "",
        "Tamano": "",
        "OtroDato": "",
        "CodigoBarras": "",
        "AfectoIGV": "",
        "AfectoISC": "",
        "ISC": "",
        "SujetoPercepcionVenta": "0",
        "TasaNormal": "",
        "TasaAgentePercepcion": "",
        "CostoPromedioPonderado": "",
        "MargenPorcentaje": "",
        "MargenUtilidad": "",
        "ValorVenta": "",
        "ValorIGV": "",
        "PrecioPromedioCompra": "",
        "FechaUltimoPrecio": "",
        "EstadoCampoCalculo": "0",
        "AfectoICBPER": "0",
        "AfectoBonificacion": "0",
        "CodigoMercaderia2": "",
        "CodigoAlterno": "",
        "IdProveedor": "",
        "Referencia": "",
        "TipoDescuento": "0",
        "ValorDescuento": 0,
        "NumeroPiezas": "",
        "IdMonedaCompra": 1,
        "CostoUnitarioCompra": "",
        "PrecioUnitarioCompra": "",
        "ReferenciaProveedor": "",
        "FechaIngresoCompra": "",
        "Aplicacion": "",
        "TipoCambioCompra": "",
        "FechaIngreso": "",
        "CodigoCorrelativoAutomatico": "",
        "IndicadorCodigoPropio": "",
        "NombreFabricante": "NO ESPECIFICADO",
        "NombreTipoExistencia": "MERCADERIA",
        "AbreviaturaUnidadMedida": "UND",
        "NombreMoneda": "SOLES",
        "NombreFamiliaProducto": "NO ESPECIFICADO",
        "IdFamiliaProducto": 0,
        "NombreSubFamiliaProducto": "NO ESPECIFICADO",
        "NombreLineaProducto": "NO ESPECIFICADO",
        "NombreMarca": "NO ESPECIFICADO",
        "IdMarca": 0,
        "NombreModelo": "NO ESPECIFICADO",
        "NombreProducto": "KORMA DE RES",
        "IndicadorEstado": "A",
        "UsuarioRegistro": "ABDUL",
        "FechaRegistro": "2022-06-28 18:02:09",
        "UsuarioModificacion": "",
        "FechaModificacion": "",
        "EstadoProducto": "1",
        "NombreLargoProducto": "KORMA DE RES",
        "CodigoTipoAfectacionIGV": "10",
        "CodigoTipoSistemaISC": "",
        "CodigoTipoPrecio": "01",
        "BloquearTipoMercaderia": 0,
        "IndicadorAfectoICBPER": false,
        "IndicadorEstadoProducto": true,
        "AnotacionesPlatoProducto": [],
        "IndicadorAfectoBonificacion": false,
        "CantidadBonificaciones": 0,
        "Bonificaciones": []
    },
    {
        "IdProducto": 506,
        "CodigoMercaderia": "7",
        "IdTipoExistencia": 1,
        "IdSubFamiliaProducto": 0,
        "IdModelo": 0,
        "IdLineaProducto": 0,
        "IdUnidadMedida": 58,
        "IdTipoSistemaISC": 0,
        "IdTipoAfectacionIGV": 1,
        "IdTipoPrecio": 1,
        "IdFabricante": 0,
        "IdMoneda": 1,
        "IdTipoTributo": 1,
        "IdOrigenMercaderia": 1,
        "SaldoFisico": "",
        "StockMinimo": "",
        "StockMaximo": "",
        "PesoUnitario": "",
        "PrecioUnitario": 150,
        "UltimoPrecio": 150,
        "FechaVencimiento": "",
        "Foto": "https://sfact.pe/15325807773/assets/img/nocover.png",
        "NumeroSerie": "",
        "NumeroMotor": "",
        "NumeroPlaca": "",
        "Ano": "",
        "Color": "",
        "Textura": "",
        "Talla": "",
        "Beneficio": "",
        "Tamano": "",
        "OtroDato": "",
        "CodigoBarras": "",
        "AfectoIGV": "",
        "AfectoISC": "",
        "ISC": "",
        "SujetoPercepcionVenta": "0",
        "TasaNormal": "",
        "TasaAgentePercepcion": "",
        "CostoPromedioPonderado": "",
        "MargenPorcentaje": "",
        "MargenUtilidad": "",
        "ValorVenta": "",
        "ValorIGV": "",
        "PrecioPromedioCompra": "",
        "FechaUltimoPrecio": "",
        "EstadoCampoCalculo": "",
        "AfectoICBPER": "0",
        "AfectoBonificacion": "0",
        "CodigoMercaderia2": "",
        "CodigoAlterno": "",
        "IdProveedor": "",
        "Referencia": "",
        "TipoDescuento": "0",
        "ValorDescuento": 0,
        "NumeroPiezas": "",
        "IdMonedaCompra": 1,
        "CostoUnitarioCompra": "",
        "PrecioUnitarioCompra": "",
        "ReferenciaProveedor": "",
        "FechaIngresoCompra": "",
        "Aplicacion": "",
        "TipoCambioCompra": "",
        "FechaIngreso": "",
        "CodigoCorrelativoAutomatico": "",
        "IndicadorCodigoPropio": "",
        "NombreFabricante": "NO ESPECIFICADO",
        "NombreTipoExistencia": "MERCADERIA",
        "AbreviaturaUnidadMedida": "UND",
        "NombreMoneda": "SOLES",
        "NombreFamiliaProducto": "NO ESPECIFICADO",
        "IdFamiliaProducto": 0,
        "NombreSubFamiliaProducto": "NO ESPECIFICADO",
        "NombreLineaProducto": "NO ESPECIFICADO",
        "NombreMarca": "NO ESPECIFICADO",
        "IdMarca": 0,
        "NombreModelo": "NO ESPECIFICADO",
        "NombreProducto": "MAQUISAPA",
        "IndicadorEstado": "A",
        "UsuarioRegistro": "ABDUL",
        "FechaRegistro": "2022-06-28 19:56:08",
        "UsuarioModificacion": "",
        "FechaModificacion": "",
        "EstadoProducto": "1",
        "NombreLargoProducto": "MAQUISAPA",
        "CodigoTipoAfectacionIGV": "10",
        "CodigoTipoSistemaISC": "",
        "CodigoTipoPrecio": "01",
        "BloquearTipoMercaderia": 0,
        "IndicadorAfectoICBPER": false,
        "IndicadorEstadoProducto": true,
        "AnotacionesPlatoProducto": [],
        "IndicadorAfectoBonificacion": false,
        "CantidadBonificaciones": 0,
        "Bonificaciones": []
    },
    {
        "IdProducto": 501,
        "CodigoMercaderia": "2",
        "IdTipoExistencia": 1,
        "IdSubFamiliaProducto": 0,
        "IdModelo": 0,
        "IdLineaProducto": 0,
        "IdUnidadMedida": 58,
        "IdTipoSistemaISC": 0,
        "IdTipoAfectacionIGV": 1,
        "IdTipoPrecio": 1,
        "IdFabricante": 0,
        "IdMoneda": 1,
        "IdTipoTributo": 1,
        "IdOrigenMercaderia": 1,
        "SaldoFisico": "",
        "StockMinimo": "",
        "StockMaximo": "",
        "PesoUnitario": "",
        "PrecioUnitario": 20,
        "UltimoPrecio": "",
        "FechaVencimiento": "",
        "Foto": "https://sfact.pe/15325807773/assets/img/Mercaderia/501/172097697_2919244945064635_6853124532915172024_N.JPG",
        "NumeroSerie": "",
        "NumeroMotor": "",
        "NumeroPlaca": "",
        "Ano": "",
        "Color": "",
        "Textura": "",
        "Talla": "",
        "Beneficio": "",
        "Tamano": "",
        "OtroDato": "",
        "CodigoBarras": "",
        "AfectoIGV": "",
        "AfectoISC": "",
        "ISC": "",
        "SujetoPercepcionVenta": "0",
        "TasaNormal": "",
        "TasaAgentePercepcion": "",
        "CostoPromedioPonderado": "",
        "MargenPorcentaje": "",
        "MargenUtilidad": "",
        "ValorVenta": "",
        "ValorIGV": "",
        "PrecioPromedioCompra": "",
        "FechaUltimoPrecio": "",
        "EstadoCampoCalculo": "0",
        "AfectoICBPER": "0",
        "AfectoBonificacion": "0",
        "CodigoMercaderia2": "",
        "CodigoAlterno": "",
        "IdProveedor": "",
        "Referencia": "",
        "TipoDescuento": "0",
        "ValorDescuento": 0,
        "NumeroPiezas": "",
        "IdMonedaCompra": 1,
        "CostoUnitarioCompra": "",
        "PrecioUnitarioCompra": "",
        "ReferenciaProveedor": "",
        "FechaIngresoCompra": "",
        "Aplicacion": "",
        "TipoCambioCompra": "",
        "FechaIngreso": "",
        "CodigoCorrelativoAutomatico": "",
        "IndicadorCodigoPropio": "",
        "NombreFabricante": "NO ESPECIFICADO",
        "NombreTipoExistencia": "MERCADERIA",
        "AbreviaturaUnidadMedida": "UND",
        "NombreMoneda": "SOLES",
        "NombreFamiliaProducto": "NO ESPECIFICADO",
        "IdFamiliaProducto": 0,
        "NombreSubFamiliaProducto": "NO ESPECIFICADO",
        "NombreLineaProducto": "NO ESPECIFICADO",
        "NombreMarca": "NO ESPECIFICADO",
        "IdMarca": 0,
        "NombreModelo": "NO ESPECIFICADO",
        "NombreProducto": "POLLO CON GARBANZO",
        "IndicadorEstado": "A",
        "UsuarioRegistro": "ABDUL",
        "FechaRegistro": "2022-06-28 18:01:28",
        "UsuarioModificacion": "",
        "FechaModificacion": "",
        "EstadoProducto": "1",
        "NombreLargoProducto": "POLLO CON GARBANZO",
        "CodigoTipoAfectacionIGV": "10",
        "CodigoTipoSistemaISC": "",
        "CodigoTipoPrecio": "01",
        "BloquearTipoMercaderia": 0,
        "IndicadorAfectoICBPER": false,
        "IndicadorEstadoProducto": true,
        "AnotacionesPlatoProducto": [],
        "IndicadorAfectoBonificacion": false,
        "CantidadBonificaciones": 0,
        "Bonificaciones": []
    }
]